In [1]:
from __future__ import print_function
import torch

In [6]:
x = torch.empty(5, 3)
print(x)

x = torch.rand(5, 3)
print(x)

x = torch.zeros(5, 3, dtype=torch.long)
print(x)

x = torch.tensor([5.5, 3])
print(x)

x = x.new_ones(5, 3, dtype=torch.double)  # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)  # override dtype!
print(x)  # result has the same size

print(x.size())

y = torch.rand(5, 3)
print(x + y)

print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# adds x to y
y.add_(x)
print(y)

print(x[:, 1])

tensor([[1.5920, 1.4922, 2.7304],
        [1.2447, 2.0868, 0.5592],
        [1.4117, 0.7680, 1.1143],
        [1.7199, 0.8654, 1.2294],
        [2.1125, 1.6094, 0.9149]])
tensor([[0.8854, 0.9205, 0.2385],
        [0.9740, 0.2049, 0.5427],
        [0.0713, 0.0554, 0.4356],
        [0.7586, 0.0704, 0.3054],
        [0.7326, 0.9139, 0.4575]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.3636, -1.1992,  1.1562],
        [ 0.3277,  0.1167, -0.3046],
        [-0.3926,  0.7979,  1.1443],
        [ 0.0831,  0.0890, -1.3584],
        [ 0.7765, -0.9108, -1.1869]])
torch.Size([5, 3])
tensor([[-1.1414, -1.1935,  1.8219],
        [ 0.6351,  0.1820,  0.0026],
        [ 0.4863,  0.8858,  1.9718],
        [ 0.5048,  0.6157, -1.2442],
        [ 1.0823, -0.6543, -0.2464]])
tensor([[-1.14

In [2]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [3]:
print(y)

tensor([-1.4570, -2.6620, -0.2485,  0.6565,  0.1385, -0.0098, -0.4255, -0.8873,
        -0.3031, -0.1469,  1.2088,  1.5974,  2.5682,  0.5068, -0.6617, -2.1359])


In [4]:
print(z)

tensor([[-1.4570, -2.6620, -0.2485,  0.6565,  0.1385, -0.0098, -0.4255, -0.8873],
        [-0.3031, -0.1469,  1.2088,  1.5974,  2.5682,  0.5068, -0.6617, -2.1359]])


In [7]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.6265])
0.626497209072113


In [8]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [9]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [10]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [11]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
